## Лабораторная работа №7

In [1]:
import re
import string
import warnings
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import pymorphy3
morph = pymorphy3.MorphAnalyzer()

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

warnings.filterwarnings('ignore')

## 1. Загрузка данных

In [2]:

df = pd.read_csv('dialogues.tsv', sep='\t')
raw_row = df.iloc[5]
raw_dialogue = raw_row['dialogue']
raw_dialogue

'<span class=participant_2>Пользователь 2: Привет!</span><br /><span class=participant_1>Пользователь 1: Привет!</span><br /><span class=participant_1>Пользователь 1: Как дела?)</span><br /><span class=participant_2>Пользователь 2: У меня все замечательно. А твои дела как? Чем занимаешься<br />по жизни?</span><br /><span class=participant_2>Пользователь 2: ?</span><br /><span class=participant_1>Пользователь 1: Рада новому знакомству! У меня тоже всё неплохо. Недавно<br />нашла работу по специальности. Я дизайнер</span><br /><span class=participant_1>Пользователь 1: А ты чем занимаешься?</span><br /><span class=participant_1>Пользователь 1: Ты откуда?</span><br /><span class=participant_2>Пользователь 2: Я продавец, выращиванию овощи и фрукты на даче и продаю<br />их. Я ещё кстати и дачница.</span><br /><span class=participant_2>Пользователь 2: Я с Украины )</span><br /><span class=participant_2>Пользователь 2: А ты откуда ?</span><br /><span class=participant_1>Пользователь 1: Круто! Я из Беларуси, Минск</span><br /><span class=participant_2>Пользователь 2: Я продавец, выращиваю овощи и фрукты на даче и продаю<br />их. Я ещё кстати и дачница.</span><br /><span class=participant_2>Пользователь 2: Как зовут тебя ?</span><br /><span class=participant_1>Пользователь 1: А я мечтаю купить дачу, но пока не могу себе этого<br />позволить(</span><br /><span class=participant_1>Пользователь 1: Катя, а тебя?</span><br /><span class=participant_2>Пользователь 2: Ира,приятно познакомится )</span><br /><span class=participant_2>Пользователь 2: А я мечтаю жить возле моря.</span><br /><span class=participant_1>Пользователь 1: Кстати, была в Украине, мне там очень понравилось<br />. Я вообще люблю путешествовать</span><br /><span class=participant_2>Пользователь 2: Обожаю море.</span><br /><span class=participant_1>Пользователь 1: Приятно познакомиться</span><br /><span class=participant_2>Пользователь 2: В каком городе Украины ты была ?</span><br /><span class=participant_1>Пользователь 1: О, я тоже люблю море))</span><br /><span class=participant_1>Пользователь 1: Много где, и в Крыму (тогда это была ещё Украина)</span><br /><span class=participant_2>Пользователь 2: Жду не дождусь лета, что бы поехать на море </span><br /><span class=participant_2>Пользователь 2: К стати, ты любишь собак?</span><br /><span class=participant_1>Пользователь 1: Мы путешествовали с друзьями на машине, поэтому много<br />где побывали. Хотя я больше люблю пешие прогулки)</span><br /><span class=participant_2>Пользователь 2: Пешие прогулки это здорово )</span><br /><span class=participant_1>Пользователь 1: О да, я люблю животных. Но я больше кошатница) У меня<br />кот Вегас и черепаха Матильда. А у тебя есть собака<br />?</span><br /><span class=participant_2>Пользователь 2: У меня аж две собаки )</span><br /><span class=participant_1>Пользователь 1: Здорово! Как их зовут?</span><br /><span class=participant_2>Пользователь 2: Аза и Герда, две девочки дворняжки)</span><br /><span class=participant_2>Пользователь 2: Подобрала их на улице, кто бросил совсем маленьких<br />, пришлось о них много заботиться)</span><br /><span class=participant_2>Пользователь 2: Подобрала их на улице, кто- то бросил совсем маленьких<br />, пришлось о них много заботиться)</span><br /><span class=participant_1>Пользователь 1: Я тоже. Планирую новое путешествие летом. Я уже побывала<br />в 12 странах. А ты любишь путешествовать?</span><br /><span class=participant_1>Пользователь 1: Ты молодец, спасла две жизни)) это здорово</span><br /><span class=participant_2>Пользователь 2: Пока что не удавалось побывать в других странах, но<br />на это лето грандиозные планы ..</span><br /><span class=participant_1>Пользователь 1: Какие?</span><br /><span class=participant_2>Пользователь 2: Поехать сначала в Германию, а потом в Россию к родственникам</span><br /><span class=participant_1>Пользователь 1: Кстати, когда я была во Львове, ходила на концерт<br />Океан Эльзи. Очень люблю эту группу и вообще рок.<br />А какую музыку ты слушаешь?</span><br /><span class=participant_2>Пользователь 2: А я рок не люблю, мне нравиться джаз)</span><br /><span class=participant_2>Пользователь 2: А вообще часто слушаю поп и рэп</span><br /><span class=participant_1>Пользователь 1: Я была в Германии, мне там очень понравилось, особенно<br />красивые замки</span><br /><span class=participant_1>Пользователь 1: Ну из джаза родился рок)</span><br /><span class=participant_2>Пользователь 2: Думаю мне тоже там понравиться. Ладно, буду я ложиться<br />спать завтра нужно рано вставать готовить кушать семье<br />) Пока.</span><br />'


## Этап 1. Очистка данных от разметки и шума

In [3]:
def clean_html(html_text: str) -> str:
    soup = BeautifulSoup(html_text, 'lxml')
   
    for br in soup.find_all('br'):
        br.replace_with('\n')
    return soup.get_text(separator=' ') 

def clean_noise(text: str) -> str:
    text = re.sub(r'[ \t]+', ' ', text)   
    text = re.sub(r'\n{2,}', '\n', text)  
    return text.strip()

clean_text = clean_html(raw_dialogue)
clean_text = clean_noise(clean_text)

print(clean_text)

Пользователь 2: Привет!
 Пользователь 1: Привет!
 Пользователь 1: Как дела?)
 Пользователь 2: У меня все замечательно. А твои дела как? Чем занимаешься
 по жизни?
 Пользователь 2: ?
 Пользователь 1: Рада новому знакомству! У меня тоже всё неплохо. Недавно
 нашла работу по специальности. Я дизайнер
 Пользователь 1: А ты чем занимаешься?
 Пользователь 1: Ты откуда?
 Пользователь 2: Я продавец, выращиванию овощи и фрукты на даче и продаю
 их. Я ещё кстати и дачница.
 Пользователь 2: Я с Украины )
 Пользователь 2: А ты откуда ?
 Пользователь 1: Круто! Я из Беларуси, Минск
 Пользователь 2: Я продавец, выращиваю овощи и фрукты на даче и продаю
 их. Я ещё кстати и дачница.
 Пользователь 2: Как зовут тебя ?
 Пользователь 1: А я мечтаю купить дачу, но пока не могу себе этого
 позволить(
 Пользователь 1: Катя, а тебя?
 Пользователь 2: Ира,приятно познакомится )
 Пользователь 2: А я мечтаю жить возле моря.
 Пользователь 1: Кстати, была в Украине, мне там очень понравилось
 . Я вообще люблю путешествовать
 Пользователь 2: Обожаю море.
 Пользователь 1: Приятно познакомиться
 Пользователь 2: В каком городе Украины ты была ?
 Пользователь 1: О, я тоже люблю море))
 Пользователь 1: Много где, и в Крыму (тогда это была ещё Украина)
 Пользователь 2: Жду не дождусь лета, что бы поехать на море
 Пользователь 2: К стати, ты любишь собак?
 Пользователь 1: Мы путешествовали с друзьями на машине, поэтому много
 где побывали. Хотя я больше люблю пешие прогулки)
 Пользователь 2: Пешие прогулки это здорово )
 Пользователь 1: О да, я люблю животных. Но я больше кошатница) У меня
 кот Вегас и черепаха Матильда. А у тебя есть собака
 ?
 Пользователь 2: У меня аж две собаки )
 Пользователь 1: Здорово! Как их зовут?
 Пользователь 2: Аза и Герда, две девочки дворняжки)
 Пользователь 2: Подобрала их на улице, кто бросил совсем маленьких
 , пришлось о них много заботиться)
 Пользователь 2: Подобрала их на улице, кто- то бросил совсем маленьких
 , пришлось о них много заботиться)
 Пользователь 1: Я тоже. Планирую новое путешествие летом. Я уже побывала
 в 12 странах. А ты любишь путешествовать?
 Пользователь 1: Ты молодец, спасла две жизни)) это здорово
 Пользователь 2: Пока что не удавалось побывать в других странах, но
 на это лето грандиозные планы ..
 Пользователь 1: Какие?
 Пользователь 2: Поехать сначала в Германию, а потом в Россию к родственникам
 Пользователь 1: Кстати, когда я была во Львове, ходила на концерт
 Океан Эльзи. Очень люблю эту группу и вообще рок.
 А какую музыку ты слушаешь?
 Пользователь 2: А я рок не люблю, мне нравиться джаз)
 Пользователь 2: А вообще часто слушаю поп и рэп
 Пользователь 1: Я была в Германии, мне там очень понравилось, особенно
 красивые замки
 Пользователь 1: Ну из джаза родился рок)
 Пользователь 2: Думаю мне тоже там понравиться. Ладно, буду я ложиться
 спать завтра нужно рано вставать готовить кушать семье
 ) Пока.


## Этап 2. Восстановление структуры диалога

In [4]:
def extract_dialogue(text: str) -> list[dict]:
 
    pattern = re.compile(
        r'Пользователь\s*(\d+)\s*:\s*(.+?)(?=(?:Пользователь\s*\d+\s*:)|$)',
        re.DOTALL
    )
    matches = pattern.findall(text)

    raw_turns = []
    for speaker_id, utterance in matches:
        utt = re.sub(r'\s+', ' ', utterance).strip()
        if utt:
            raw_turns.append({'speaker': f'Пользователь_{speaker_id}', 'text': utt})

    # Объединяем подряд идущие реплики одного участника
    merged = []
    for turn in raw_turns:
        if merged and merged[-1]['speaker'] == turn['speaker']:
            merged[-1]['text'] += ' ' + turn['text']
        else:
            merged.append({'speaker': turn['speaker'], 'text': turn['text']})

    return merged

dialogue = extract_dialogue(clean_text)

print('Структурированный диалог:')

for turn in dialogue:
    print(f"[{turn['speaker']}]: {turn['text']}")

print(f'Всего реплик (после объединения): {len(dialogue)}')

Структурированный диалог:
[Пользователь_2]: Привет!
[Пользователь_1]: Привет! Как дела?)
[Пользователь_2]: У меня все замечательно. А твои дела как? Чем занимаешься по жизни? ?
[Пользователь_1]: Рада новому знакомству! У меня тоже всё неплохо. Недавно нашла работу по специальности. Я дизайнер А ты чем занимаешься? Ты откуда?
[Пользователь_2]: Я продавец, выращиванию овощи и фрукты на даче и продаю их. Я ещё кстати и дачница. Я с Украины ) А ты откуда ?
[Пользователь_1]: Круто! Я из Беларуси, Минск
[Пользователь_2]: Я продавец, выращиваю овощи и фрукты на даче и продаю их. Я ещё кстати и дачница. Как зовут тебя ?
[Пользователь_1]: А я мечтаю купить дачу, но пока не могу себе этого позволить( Катя, а тебя?
[Пользователь_2]: Ира,приятно познакомится ) А я мечтаю жить возле моря.
[Пользователь_1]: Кстати, была в Украине, мне там очень понравилось . Я вообще люблю путешествовать
[Пользователь_2]: Обожаю море.
[Пользователь_1]: Приятно познакомиться
[Пользователь_2]: В каком городе Украины ты была ?
[Пользователь_1]: О, я тоже люблю море)) Много где, и в Крыму (тогда это была ещё Украина)
[Пользователь_2]: Жду не дождусь лета, что бы поехать на море К стати, ты любишь собак?
[Пользователь_1]: Мы путешествовали с друзьями на машине, поэтому много где побывали. Хотя я больше люблю пешие прогулки)
[Пользователь_2]: Пешие прогулки это здорово )
[Пользователь_1]: О да, я люблю животных. Но я больше кошатница) У меня кот Вегас и черепаха Матильда. А у тебя есть собака ?
[Пользователь_2]: У меня аж две собаки )
[Пользователь_1]: Здорово! Как их зовут?
[Пользователь_2]: Аза и Герда, две девочки дворняжки) Подобрала их на улице, кто бросил совсем маленьких , пришлось о них много заботиться) Подобрала их на улице, кто- то бросил совсем маленьких , пришлось о них много заботиться)
[Пользователь_1]: Я тоже. Планирую новое путешествие летом. Я уже побывала в 12 странах. А ты любишь путешествовать? Ты молодец, спасла две жизни)) это здорово
[Пользователь_2]: Пока что не удавалось побывать в других странах, но на это лето грандиозные планы ..
[Пользователь_1]: Какие?
[Пользователь_2]: Поехать сначала в Германию, а потом в Россию к родственникам
[Пользователь_1]: Кстати, когда я была во Львове, ходила на концерт Океан Эльзи. Очень люблю эту группу и вообще рок. А какую музыку ты слушаешь?
[Пользователь_2]: А я рок не люблю, мне нравиться джаз) А вообще часто слушаю поп и рэп
[Пользователь_1]: Я была в Германии, мне там очень понравилось, особенно красивые замки Ну из джаза родился рок)
[Пользователь_2]: Думаю мне тоже там понравиться. Ладно, буду я ложиться спать завтра нужно рано вставать готовить кушать семье ) Пока.
Всего реплик (после объединения): 29

In [5]:
dialogue_df = pd.DataFrame(dialogue)
print(dialogue_df.to_string(index=True))

           speaker                                                                                                                                                                                                                 text
0   Пользователь_2                                                                                                                                                                                                              Привет!
1   Пользователь_1                                                                                                                                                                                                   Привет! Как дела?)
2   Пользователь_2                                                                                                                                                У меня все замечательно. А твои дела как? Чем занимаешься по жизни? ?
3   Пользователь_1                                                                                  Рада новому знакомству! У меня тоже всё неплохо. Недавно нашла работу по специальности. Я дизайнер А ты чем занимаешься? Ты откуда?
4   Пользователь_2                                                                                                      Я продавец, выращиванию овощи и фрукты на даче и продаю их. Я ещё кстати и дачница. Я с Украины ) А ты откуда ?
5   Пользователь_1                                                                                                                                                                                          Круто! Я из Беларуси, Минск
6   Пользователь_2                                                                                                                   Я продавец, выращиваю овощи и фрукты на даче и продаю их. Я ещё кстати и дачница. Как зовут тебя ?
7   Пользователь_1                                                                                                                                          А я мечтаю купить дачу, но пока не могу себе этого позволить( Катя, а тебя?
8   Пользователь_2                                                                                                                                                               Ира,приятно познакомится ) А я мечтаю жить возле моря.
9   Пользователь_1                                                                                                                                    Кстати, была в Украине, мне там очень понравилось . Я вообще люблю путешествовать
10  Пользователь_2                                                                                                                                                                                                         Обожаю море.
11  Пользователь_1                                                                                                                                                                                                Приятно познакомиться
12  Пользователь_2                                                                                                                                                                                     В каком городе Украины ты была ?
13  Пользователь_1                                                                                                                                             О, я тоже люблю море)) Много где, и в Крыму (тогда это была ещё Украина)
14  Пользователь_2                                                                                                                                                Жду не дождусь лета, что бы поехать на море К стати, ты любишь собак?
15  Пользователь_1                                                                                                              Мы путешествовали с друзьями на машине, поэтому много где побывали. Хотя я больше люблю пешие прогулки)
16  Пользователь_2                                                                                                                                                                                         Пешие прогулки это здорово )
17  Пользователь_1                                                                                                          О да, я люблю животных. Но я больше кошатница) У меня кот Вегас и черепаха Матильда. А у тебя есть собака ?
18  Пользователь_2                                                                                                                                                                                               У меня аж две собаки )
19  Пользователь_1                                                                                                                                                                                               Здорово! Как их зовут?
20  Пользователь_2  Аза и Герда, две девочки дворняжки) Подобрала их на улице, кто бросил совсем маленьких , пришлось о них много заботиться) Подобрала их на улице, кто- то бросил совсем маленьких , пришлось о них много заботиться)
21  Пользователь_1                                                                        Я тоже. Планирую новое путешествие летом. Я уже побывала в 12 странах. А ты любишь путешествовать? Ты молодец, спасла две жизни)) это здорово
22  Пользователь_2                                                                                                                                 Пока что не удавалось побывать в других странах, но на это лето грандиозные планы ..
23  Пользователь_1                                                                                                                                                                                                               Какие?
24  Пользователь_2                                                                                                                                                         Поехать сначала в Германию, а потом в Россию к родственникам
25  Пользователь_1                                                                                      Кстати, когда я была во Львове, ходила на концерт Океан Эльзи. Очень люблю эту группу и вообще рок. А какую музыку ты слушаешь?
26  Пользователь_2                                                                                                                                                А я рок не люблю, мне нравиться джаз) А вообще часто слушаю поп и рэп
27  Пользователь_1                                                                                                                       Я была в Германии, мне там очень понравилось, особенно красивые замки Ну из джаза родился рок)
28  Пользователь_2                                                                                                Думаю мне тоже там понравиться. Ладно, буду я ложиться спать завтра нужно рано вставать готовить кушать семье ) Пока.


## Этап 3. Нормализация текста

In [6]:
RUSSIAN_STOPWORDS = set(stopwords.words('russian'))
EXTRA_STOPWORDS = {'это', 'такой', 'вот', 'ну', 'да', 'нет', 'ещё', 'тоже'}
RUSSIAN_STOPWORDS.update(EXTRA_STOPWORDS)

def normalize_text(text: str,
                   remove_digits: bool = True,
                   remove_stopwords: bool = True) -> list[str]:
   
    text = text.lower()
    # Удаляем пунктуацию
    punct_pattern = r'[{}]'.format(re.escape(string.punctuation + '«»—…'))
    text = re.sub(punct_pattern, ' ', text)
    if remove_digits:
        text = re.sub(r'\d+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    tokens = word_tokenize(text, language='russian')

    if remove_stopwords:
        tokens = [t for t in tokens
                  if t not in RUSSIAN_STOPWORDS and len(t) > 1]
    return tokens

dialogue_df['tokens'] = dialogue_df['text'].apply(normalize_text)

print('Результат токенизации:')
for _, row in dialogue_df.iterrows():
    print(f"[{row['speaker']}]: {row['tokens']}")

Результат токенизации:
[Пользователь_2]: ['привет']
[Пользователь_1]: ['привет', 'дела']
[Пользователь_2]: ['замечательно', 'твои', 'дела', 'занимаешься', 'жизни']
[Пользователь_1]: ['рада', 'новому', 'знакомству', 'всё', 'неплохо', 'недавно', 'нашла', 'работу', 'специальности', 'дизайнер', 'занимаешься', 'откуда']
[Пользователь_2]: ['продавец', 'выращиванию', 'овощи', 'фрукты', 'даче', 'продаю', 'кстати', 'дачница', 'украины', 'откуда']
[Пользователь_1]: ['круто', 'беларуси', 'минск']
[Пользователь_2]: ['продавец', 'выращиваю', 'овощи', 'фрукты', 'даче', 'продаю', 'кстати', 'дачница', 'зовут']
[Пользователь_1]: ['мечтаю', 'купить', 'дачу', 'пока', 'могу', 'позволить', 'катя']
[Пользователь_2]: ['ира', 'приятно', 'познакомится', 'мечтаю', 'жить', 'возле', 'моря']
[Пользователь_1]: ['кстати', 'украине', 'очень', 'понравилось', 'вообще', 'люблю', 'путешествовать']
[Пользователь_2]: ['обожаю', 'море']
[Пользователь_1]: ['приятно', 'познакомиться']
[Пользователь_2]: ['каком', 'городе', 'украины']
[Пользователь_1]: ['люблю', 'море', 'крыму', 'украина']
[Пользователь_2]: ['жду', 'дождусь', 'лета', 'поехать', 'море', 'стати', 'любишь', 'собак']
[Пользователь_1]: ['путешествовали', 'друзьями', 'машине', 'поэтому', 'побывали', 'хотя', 'люблю', 'пешие', 'прогулки']
[Пользователь_2]: ['пешие', 'прогулки', 'здорово']
[Пользователь_1]: ['люблю', 'животных', 'кошатница', 'кот', 'вегас', 'черепаха', 'матильда', 'собака']
[Пользователь_2]: ['аж', 'две', 'собаки']
[Пользователь_1]: ['здорово', 'зовут']
[Пользователь_2]: ['аза', 'герда', 'две', 'девочки', 'дворняжки', 'подобрала', 'улице', 'бросил', 'маленьких', 'пришлось', 'заботиться', 'подобрала', 'улице', 'бросил', 'маленьких', 'пришлось', 'заботиться']
[Пользователь_1]: ['планирую', 'новое', 'путешествие', 'летом', 'побывала', 'странах', 'любишь', 'путешествовать', 'молодец', 'спасла', 'две', 'жизни', 'здорово']
[Пользователь_2]: ['пока', 'удавалось', 'побывать', 'других', 'странах', 'лето', 'грандиозные', 'планы']
[Пользователь_1]: ['какие']
[Пользователь_2]: ['поехать', 'сначала', 'германию', 'россию', 'родственникам']
[Пользователь_1]: ['кстати', 'львове', 'ходила', 'концерт', 'океан', 'эльзи', 'очень', 'люблю', 'группу', 'вообще', 'рок', 'какую', 'музыку', 'слушаешь']
[Пользователь_2]: ['рок', 'люблю', 'нравиться', 'джаз', 'вообще', 'часто', 'слушаю', 'поп', 'рэп']
[Пользователь_1]: ['германии', 'очень', 'понравилось', 'особенно', 'красивые', 'замки', 'джаза', 'родился', 'рок']
[Пользователь_2]: ['думаю', 'понравиться', 'ладно', 'буду', 'ложиться', 'спать', 'завтра', 'нужно', 'рано', 'вставать', 'готовить', 'кушать', 'семье', 'пока']


## Этап 4. Морфологическая обработка (лемматизация + стемминг)

In [7]:
def lemmatize(tokens: list[str]) -> list[str]:
    return [morph.parse(t)[0].normal_form for t in tokens]  # самый вероятный разбор + нач. форма

dialogue_df['lemmas'] = dialogue_df['tokens'].apply(lemmatize)

for _, row in dialogue_df.iterrows():
    print(f"[{row['speaker']}]: {row['lemmas']}")

[Пользователь_2]: ['привет']
[Пользователь_1]: ['привет', 'дело']
[Пользователь_2]: ['замечательный', 'твой', 'дело', 'заниматься', 'жизнь']
[Пользователь_1]: ['рада', 'новый', 'знакомство', 'всё', 'неплохо', 'недавно', 'найти', 'работа', 'специальность', 'дизайнер', 'заниматься', 'откуда']
[Пользователь_2]: ['продавец', 'выращивание', 'овощ', 'фрукт', 'дача', 'продавать', 'кстати', 'дачница', 'украина', 'откуда']
[Пользователь_1]: ['круто', 'беларусь', 'минск']
[Пользователь_2]: ['продавец', 'выращивать', 'овощ', 'фрукт', 'дача', 'продавать', 'кстати', 'дачница', 'звать']
[Пользователь_1]: ['мечтать', 'купить', 'дача', 'пока', 'мочь', 'позволить', 'катя']
[Пользователь_2]: ['ир', 'приятно', 'познакомиться', 'мечтать', 'жить', 'возле', 'море']
[Пользователь_1]: ['кстати', 'украина', 'очень', 'понравиться', 'вообще', 'любить', 'путешествовать']
[Пользователь_2]: ['обожать', 'море']
[Пользователь_1]: ['приятно', 'познакомиться']
[Пользователь_2]: ['какой', 'город', 'украина']
[Пользователь_1]: ['любить', 'море', 'крым', 'украина']
[Пользователь_2]: ['ждать', 'дождаться', 'лето', 'поехать', 'море', 'стать', 'любить', 'собака']
[Пользователь_1]: ['путешествовать', 'друг', 'машина', 'поэтому', 'побывать', 'хотя', 'любить', 'пеший', 'прогулка']
[Пользователь_2]: ['пеший', 'прогулка', 'здорово']
[Пользователь_1]: ['любить', 'животное', 'кошатница', 'кот', 'вегаснуть', 'черепаха', 'матильда', 'собака']
[Пользователь_2]: ['аж', 'два', 'собака']
[Пользователь_1]: ['здорово', 'звать']
[Пользователь_2]: ['аз', 'герд', 'два', 'девочка', 'дворняжка', 'подобрать', 'улица', 'бросить', 'маленький', 'прийтись', 'заботиться', 'подобрать', 'улица', 'бросить', 'маленький', 'прийтись', 'заботиться']
[Пользователь_1]: ['планировать', 'новый', 'путешествие', 'лето', 'побывать', 'страна', 'любить', 'путешествовать', 'молодец', 'спасти', 'два', 'жизнь', 'здорово']
[Пользователь_2]: ['пока', 'удаваться', 'побывать', 'другой', 'страна', 'лето', 'грандиозный', 'план']
[Пользователь_1]: ['какой']
[Пользователь_2]: ['поехать', 'сначала', 'германия', 'россия', 'родственник']
[Пользователь_1]: ['кстати', 'львов', 'ходить', 'концерт', 'океан', 'эльзить', 'очень', 'любить', 'группа', 'вообще', 'рок', 'какой', 'музыка', 'слушать']
[Пользователь_2]: ['рок', 'любить', 'нравиться', 'джаз', 'вообще', 'часто', 'слушать', 'поп', 'рэп']
[Пользователь_1]: ['германия', 'очень', 'понравиться', 'особенно', 'красивый', 'замок', 'джаз', 'родиться', 'рок']
[Пользователь_2]: ['думать', 'понравиться', 'ладный', 'быть', 'ложиться', 'спать', 'завтра', 'нужно', 'рано', 'вставать', 'готовить', 'кушать', 'семья', 'пока']

In [8]:
from nltk.stem.snowball import SnowballStemmer

stemmer = SnowballStemmer('russian')

def stem(tokens: list[str]) -> list[str]:
    return [stemmer.stem(t) for t in tokens]

dialogue_df['stems'] = dialogue_df['tokens'].apply(stem)

print('После стемминга:')
for _, row in dialogue_df.iterrows():
    print(f"[{row['speaker']}]: {row['stems']}")

После стемминга:
[Пользователь_2]: ['привет']
[Пользователь_1]: ['привет', 'дел']
[Пользователь_2]: ['замечательн', 'тво', 'дел', 'занима', 'жизн']
[Пользователь_1]: ['рад', 'нов', 'знакомств', 'все', 'неплох', 'недавн', 'нашл', 'работ', 'специальн', 'дизайнер', 'занима', 'откуд']
[Пользователь_2]: ['продавец', 'выращиван', 'овощ', 'фрукт', 'дач', 'прода', 'кстат', 'дачниц', 'украин', 'откуд']
[Пользователь_1]: ['крут', 'беларус', 'минск']
[Пользователь_2]: ['продавец', 'выращива', 'овощ', 'фрукт', 'дач', 'прода', 'кстат', 'дачниц', 'зовут']
[Пользователь_1]: ['мечта', 'куп', 'дач', 'пок', 'мог', 'позвол', 'кат']
[Пользователь_2]: ['ир', 'приятн', 'познаком', 'мечта', 'жит', 'возл', 'мор']
[Пользователь_1]: ['кстат', 'украин', 'очен', 'понрав', 'вообщ', 'любл', 'путешествова']
[Пользователь_2]: ['обожа', 'мор']
[Пользователь_1]: ['приятн', 'познаком']
[Пользователь_2]: ['как', 'город', 'украин']
[Пользователь_1]: ['любл', 'мор', 'крым', 'украин']
[Пользователь_2]: ['жду', 'дожд', 'лет', 'поеха', 'мор', 'стат', 'люб', 'собак']
[Пользователь_1]: ['путешествова', 'друз', 'машин', 'поэт', 'побыва', 'хот', 'любл', 'пеш', 'прогулк']
[Пользователь_2]: ['пеш', 'прогулк', 'здоров']
[Пользователь_1]: ['любл', 'животн', 'кошатниц', 'кот', 'вегас', 'черепах', 'матильд', 'собак']
[Пользователь_2]: ['аж', 'две', 'собак']
[Пользователь_1]: ['здоров', 'зовут']
[Пользователь_2]: ['аз', 'герд', 'две', 'девочк', 'дворняжк', 'подобра', 'улиц', 'брос', 'маленьк', 'пришл', 'забот', 'подобра', 'улиц', 'брос', 'маленьк', 'пришл', 'забот']
[Пользователь_1]: ['планир', 'нов', 'путешеств', 'лет', 'побыва', 'стран', 'люб', 'путешествова', 'молодец', 'спасл', 'две', 'жизн', 'здоров']
[Пользователь_2]: ['пок', 'удава', 'побыва', 'друг', 'стран', 'лет', 'грандиозн', 'план']
[Пользователь_1]: ['как']
[Пользователь_2]: ['поеха', 'снача', 'герман', 'росс', 'родственник']
[Пользователь_1]: ['кстат', 'львов', 'ход', 'концерт', 'океа', 'эльз', 'очен', 'любл', 'групп', 'вообщ', 'рок', 'как', 'музык', 'слуша']
[Пользователь_2]: ['рок', 'любл', 'нрав', 'джаз', 'вообщ', 'част', 'слуша', 'поп', 'рэп']
[Пользователь_1]: ['герман', 'очен', 'понрав', 'особен', 'красив', 'замк', 'джаз', 'род', 'рок']
[Пользователь_2]: ['дума', 'понрав', 'ладн', 'буд', 'лож', 'спат', 'завтр', 'нужн', 'ран', 'встава', 'готов', 'куша', 'сем', 'пок']

In [9]:
compare_df = dialogue_df[['speaker', 'text', 'tokens', 'lemmas', 'stems']].copy()
compare_df.columns = ['Участник', 'Исходный текст', 'Токены', 'Леммы', 'Стеммы']
compare_df

,Участник,Исходный текст,Токены,Леммы,Стеммы
0,Пользователь_2,Привет!,[привет],[привет],[привет]
1,Пользователь_1,Привет! Как дела?),"[привет, дела]","[привет, дело]","[привет, дел]"
2,Пользователь_2,У меня все замечательно. А твои дела как? Чем ...,"[замечательно, твои, дела, занимаешься, жизни]","[замечательный, твой, дело, заниматься, жизнь]","[замечательн, тво, дел, занима, жизн]"
3,Пользователь_1,Рада новому знакомству! У меня тоже всё неплох...,"[рада, новому, знакомству, всё, неплохо, недав...","[рада, новый, знакомство, всё, неплохо, недавн...","[рад, нов, знакомств, все, неплох, недавн, наш..."
4,Пользователь_2,"Я продавец, выращиванию овощи и фрукты на даче...","[продавец, выращиванию, овощи, фрукты, даче, п...","[продавец, выращивание, овощ, фрукт, дача, про...","[продавец, выращиван, овощ, фрукт, дач, прода,..."
5,Пользователь_1,"Круто! Я из Беларуси, Минск","[круто, беларуси, минск]","[круто, беларусь, минск]","[крут, беларус, минск]"
6,Пользователь_2,"Я продавец, выращиваю овощи и фрукты на даче и...","[продавец, выращиваю, овощи, фрукты, даче, про...","[продавец, выращивать, овощ, фрукт, дача, прод...","[продавец, выращива, овощ, фрукт, дач, прода, ..."
7,Пользователь_1,"А я мечтаю купить дачу, но пока не могу себе э...","[мечтаю, купить, дачу, пока, могу, позволить, ...","[мечтать, купить, дача, пока, мочь, позволить,...","[мечта, куп, дач, пок, мог, позвол, кат]"
8,Пользователь_2,"Ира,приятно познакомится ) А я мечтаю жить воз...","[ира, приятно, познакомится, мечтаю, жить, воз...","[ир, приятно, познакомиться, мечтать, жить, во...","[ир, приятн, познаком, мечта, жит, возл, мор]"
9,Пользователь_1,"Кстати, была в Украине, мне там очень понравил...","[кстати, украине, очень, понравилось, вообще, ...","[кстати, украина, очень, понравиться, вообще, ...","[кстат, украин, очен, понрав, вообщ, любл, пут..."
10,Пользователь_2,Обожаю море.,"[обожаю, море]","[обожать, море]","[обожа, мор]"
11,Пользователь_1,Приятно познакомиться,"[приятно, познакомиться]","[приятно, познакомиться]","[приятн, познаком]"
12,Пользователь_2,В каком городе Украины ты была ?,"[каком, городе, украины]","[какой, город, украина]","[как, город, украин]"
13,Пользователь_1,"О, я тоже люблю море)) Много где, и в Крыму (т...","[люблю, море, крыму, украина]","[любить, море, крым, украина]","[любл, мор, крым, украин]"
14,Пользователь_2,"Жду не дождусь лета, что бы поехать на море К ...","[жду, дождусь, лета, поехать, море, стати, люб...","[ждать, дождаться, лето, поехать, море, стать,...","[жду, дожд, лет, поеха, мор, стат, люб, собак]"
15,Пользователь_1,"Мы путешествовали с друзьями на машине, поэтом...","[путешествовали, друзьями, машине, поэтому, по...","[путешествовать, друг, машина, поэтому, побыва...","[путешествова, друз, машин, поэт, побыва, хот,..."
16,Пользователь_2,Пешие прогулки это здорово ),"[пешие, прогулки, здорово]","[пеший, прогулка, здорово]","[пеш, прогулк, здоров]"
17,Пользователь_1,"О да, я люблю животных. Но я больше кошатница)...","[люблю, животных, кошатница, кот, вегас, череп...","[любить, животное, кошатница, кот, вегаснуть, ...","[любл, животн, кошатниц, кот, вегас, черепах, ..."
18,Пользователь_2,У меня аж две собаки ),"[аж, две, собаки]","[аж, два, собака]","[аж, две, собак]"
19,Пользователь_1,Здорово! Как их зовут?,"[здорово, зовут]","[здорово, звать]","[здоров, зовут]"
20,Пользователь_2,"Аза и Герда, две девочки дворняжки) Подобрала ...","[аза, герда, две, девочки, дворняжки, подобрал...","[аз, герд, два, девочка, дворняжка, подобрать,...","[аз, герд, две, девочк, дворняжк, подобра, ули..."
21,Пользователь_1,Я тоже. Планирую новое путешествие летом. Я уж...,"[планирую, новое, путешествие, летом, побывала...","[планировать, новый, путешествие, лето, побыва...","[планир, нов, путешеств, лет, побыва, стран, л..."
22,Пользователь_2,Пока что не удавалось побывать в других страна...,"[пока, удавалось, побывать, других, странах, л...","[пока, удаваться, побывать, другой, страна, ле...","[пок, удава, побыва, друг, стран, лет, грандио..."
23,Пользователь_1,Какие?,[какие],[какой],[как]
24,Пользователь_2,"Поехать сначала в Германию, а потом в Россию к...","[поехать, сначала, германию, россию, родственн...","[поехать, сначала, германия, россия, родственник]","[поеха, снача, герман, росс, родственник]"
25,Пользователь_1,"Кстати, когда я была во Львове, ходила на конц...","[кстати, львове, ходила, концерт, океан, эльзи...","[кстати, львов, ходить, концерт, океан, эльзит...","[кстат, львов, ход, концерт, океа, эльз, очен,..."
26,Пользователь_2,"А я рок не люблю, мне нравиться джаз) А вообще...","[рок, люблю, нравиться, джаз, вообще, часто, с...","[рок, любить, нравиться, джаз, вообще, часто, ...","[рок, любл, нрав, джаз, вообщ, част, слуша, по..."
27,Пользователь_1,"Я была в Германии, мне там очень понравилось, ...","[германии, очень, понравилось, особенно, краси...","[германия, очень, понравиться, особенно, краси...","[герман, очен, понрав, особен, красив, замк, д..."
28,Пользователь_2,"Думаю мне тоже там понравиться. Ладно, буду я ...","[думаю, понравиться, ладно, буду, ложиться, сп...","[думать, понравиться, ладный, быть, ложиться, ...","[дума, понрав, ладн, буд, лож, спат, завтр, ну..."


## Этап 5. Числовое представление текста

In [10]:
# каждая реплика - строка с леммами
corpus_lemmas = [' '.join(row) for row in dialogue_df['lemmas']]

# весь диалог как один текст 
all_tokens_lemmas = [t for row in dialogue_df['lemmas'] for t in row]

print('Корпус (реплики):')
for i, doc in enumerate(corpus_lemmas):
    print(f'  [{i}] {doc}')

Корпус (реплики):
  [0] привет
  [1] привет дело
  [2] замечательный твой дело заниматься жизнь
  [3] рада новый знакомство всё неплохо недавно найти работа специальность дизайнер заниматься откуда
  [4] продавец выращивание овощ фрукт дача продавать кстати дачница украина откуда
  [5] круто беларусь минск
  [6] продавец выращивать овощ фрукт дача продавать кстати дачница звать
  [7] мечтать купить дача пока мочь позволить катя
  [8] ир приятно познакомиться мечтать жить возле море
  [9] кстати украина очень понравиться вообще любить путешествовать
  [10] обожать море
  [11] приятно познакомиться
  [12] какой город украина
  [13] любить море крым украина
  [14] ждать дождаться лето поехать море стать любить собака
  [15] путешествовать друг машина поэтому побывать хотя любить пеший прогулка
  [16] пеший прогулка здорово
  [17] любить животное кошатница кот вегаснуть черепаха матильда собака
  [18] аж два собака
  [19] здорово звать
  [20] аз герд два девочка дворняжка подобрать улица бросить маленький прийтись заботиться подобрать улица бросить маленький прийтись заботиться
  [21] планировать новый путешествие лето побывать страна любить путешествовать молодец спасти два жизнь здорово
  [22] пока удаваться побывать другой страна лето грандиозный план
  [23] какой
  [24] поехать сначала германия россия родственник
  [25] кстати львов ходить концерт океан эльзить очень любить группа вообще рок какой музыка слушать
  [26] рок любить нравиться джаз вообще часто слушать поп рэп
  [27] германия очень понравиться особенно красивый замок джаз родиться рок
  [28] думать понравиться ладный быть ложиться спать завтра нужно рано вставать готовить кушать семья пока

### 5.1 Bag of Words (CountVectorizer)

In [11]:
cv = CountVectorizer()
bow_matrix = cv.fit_transform(corpus_lemmas)

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=cv.get_feature_names_out(),
    index=[f'Реплика {i+1}' for i in range(len(corpus_lemmas))]
)
display(bow_df)

,аж,аз,беларусь,бросить,быть,вегаснуть,возле,вообще,вставать,всё,...,твой,удаваться,украина,улица,фрукт,ходить,хотя,часто,черепаха,эльзить
Реплика 1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Реплика 4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Реплика 5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
Реплика 6,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Реплика 8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 9,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 10,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
Реплика 11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 13,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Реплика 14,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Реплика 15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Реплика 17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Реплика 19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 21,0,1,0,2,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
Реплика 22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 23,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Реплика 24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 26,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
Реплика 27,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
Реплика 28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 29,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

### 5.2 TF-IDF

In [12]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus_lemmas)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray().round(3),
    columns=tfidf.get_feature_names_out(),
    index=[f'Реплика {i+1}' for i in range(len(corpus_lemmas))]
)
display(tfidf_df)

,аж,аз,беларусь,бросить,быть,вегаснуть,возле,вообще,вставать,всё,...,твой,удаваться,украина,улица,фрукт,ходить,хотя,часто,черепаха,эльзить
Реплика 1,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 2,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 3,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.478,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 4,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.296,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 5,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.274,0.000,0.324,0.000,0.000,0.000,0.000,0.000
Реплика 6,0.000,0.000,0.577,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 7,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.337,0.000,0.000,0.000,0.000,0.000
Реплика 8,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 9,0.000,0.000,0.000,0.000,0.000,0.000,0.41,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 10,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.400,0.000,0.000,...,0.000,0.000,0.370,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 11,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 12,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 13,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.504,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 14,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.477,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 15,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 16,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.371,0.000,0.000,0.000
Реплика 17,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 18,0.000,0.000,0.000,0.000,0.000,0.378,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.378,0.000
Реплика 19,0.656,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 20,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 21,0.000,0.187,0.000,0.374,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.374,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 22,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 23,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.384,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 24,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 25,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 26,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.241,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.297,0.000,0.000,0.000,0.297
Реплика 27,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.302,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.371,0.000,0.000
Реплика 28,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
Реплика 29,0.000,0.000,0.000,0.000,0.274,0.000,0.00,0.000,0.274,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

### 5.3 N-граммы (биграммы)

In [13]:
ngram_vec = CountVectorizer(ngram_range=(2, 2))  # биграммы
ngram_matrix = ngram_vec.fit_transform(corpus_lemmas)

ngram_df = pd.DataFrame(
    ngram_matrix.toarray(),
    columns=ngram_vec.get_feature_names_out(),
    index=[f'Реплика {i+1}' for i in range(len(corpus_lemmas))]
)

nonzero_cols = ngram_df.loc[:, (ngram_df != 0).any(axis=0)]
print('Биграммы (N-граммы, n=2):')
if nonzero_cols.empty:
    print('Биграмм не обнаружено (слишком мало слов в репликах).')
else:
    display(nonzero_cols)

Биграммы (N-граммы, n=2):

,аж два,аз герд,беларусь минск,бросить маленький,быть ложиться,вегаснуть черепаха,возле море,вообще любить,вообще рок,вообще часто,...,удаваться побывать,украина откуда,украина очень,улица бросить,фрукт дача,ходить концерт,хотя любить,часто слушать,черепаха матильда,эльзить очень
Реплика 1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 5,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
Реплика 6,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Реплика 8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 9,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 10,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
Реплика 11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Реплика 17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Реплика 19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 21,0,1,0,2,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
Реплика 22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 23,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Реплика 24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 26,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
Реплика 27,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
Реплика 28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 29,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
print("Bag of Words (топ-10 слов по частоте)")
top_words = bow_df.sum().sort_values(ascending=False).head(10)
display(pd.DataFrame(top_words, columns=['Частота']).T)

print("\nTF-IDF (только ненулевые значения)")
for i, row in tfidf_df.iterrows():
    nonzero = row[row > 0].sort_values(ascending=False)
    print(f"\n{i}:")
    display(pd.DataFrame(nonzero).T.round(3))

    print("\nN-граммы (биграммы, только встречающиеся)")
nonzero_ngrams = ngram_df.loc[:, (ngram_df > 0).any()].head(10)

display(nonzero_ngrams)

Bag of Words (топ-10 слов по частоте)

,любить,кстати,море,украина,путешествовать,лето,собака,побывать,два,пока
Частота,8,4,4,4,3,3,3,3,3,3

TF-IDF (только ненулевые значения)

Реплика 1:

           привет
Реплика 1     1.0

N-граммы (биграммы, только встречающиеся)

Реплика 2:

            дело  привет
Реплика 2  0.707   0.707

N-граммы (биграммы, только встречающиеся)

Реплика 3:

           замечательный   твой   дело  жизнь  заниматься
Реплика 3          0.478  0.478  0.426  0.426       0.426

N-граммы (биграммы, только встречающиеся)

Реплика 4:

,всё,дизайнер,знакомство,найти,недавно,неплохо,работа,рада,специальность,заниматься,новый,откуда
Реплика 4,0.296,0.296,0.296,0.296,0.296,0.296,0.296,0.296,0.296,0.264,0.264,0.264

N-граммы (биграммы, только встречающиеся)

Реплика 5:

,выращивание,дачница,овощ,откуда,продавать,продавец,фрукт,дача,кстати,украина
Реплика 5,0.364,0.324,0.324,0.324,0.324,0.324,0.324,0.296,0.274,0.274

N-граммы (биграммы, только встречающиеся)

Реплика 6:

           беларусь  круто  минск
Реплика 6     0.577  0.577  0.577

N-граммы (биграммы, только встречающиеся)

Реплика 7:

,выращивать,дачница,звать,овощ,продавать,продавец,фрукт,дача,кстати
Реплика 7,0.378,0.337,0.337,0.337,0.337,0.337,0.337,0.308,0.285

N-граммы (биграммы, только встречающиеся)

Реплика 8:

            катя  купить   мочь  позволить  мечтать   дача   пока
Реплика 8  0.404   0.404  0.404      0.404     0.36  0.329  0.329

N-граммы (биграммы, только встречающиеся)

Реплика 9:

           возле  жить    ир  мечтать  познакомиться  приятно   море
Реплика 9   0.41  0.41  0.41    0.365          0.365    0.365  0.309

N-граммы (биграммы, только встречающиеся)

Реплика 10:

,вообще,очень,понравиться,путешествовать,кстати,украина,любить
Реплика 10,0.4,0.4,0.4,0.4,0.37,0.37,0.292

N-граммы (биграммы, только встречающиеся)

Реплика 11:

            обожать   море
Реплика 11    0.799  0.601

N-граммы (биграммы, только встречающиеся)

Реплика 12:

            познакомиться  приятно
Реплика 12          0.707    0.707

N-граммы (биграммы, только встречающиеся)

Реплика 13:

            город  какой  украина
Реплика 13   0.67  0.545    0.504

N-граммы (биграммы, только встречающиеся)

Реплика 14:

             крым   море  украина  любить
Реплика 14  0.634  0.477    0.477   0.377

N-граммы (биграммы, только встречающиеся)

Реплика 15:

            дождаться  ждать  стать  поехать   лето  собака   море  любить
Реплика 15      0.407  0.407  0.407    0.363  0.331   0.331  0.306   0.242

N-граммы (биграммы, только встречающиеся)

Реплика 16:

,друг,машина,поэтому,хотя,пеший,прогулка,побывать,путешествовать,любить
Реплика 16,0.371,0.371,0.371,0.371,0.331,0.331,0.302,0.302,0.221

N-граммы (биграммы, только встречающиеся)

Реплика 17:

            пеший  прогулка  здорово
Реплика 17  0.594     0.594    0.542

N-граммы (биграммы, только встречающиеся)

Реплика 18:

,вегаснуть,животное,кот,кошатница,матильда,черепаха,собака,любить
Реплика 18,0.378,0.378,0.378,0.378,0.378,0.378,0.307,0.224

N-граммы (биграммы, только встречающиеся)

Реплика 19:

               аж    два  собака
Реплика 19  0.656  0.534   0.534

N-граммы (биграммы, только встречающиеся)

Реплика 20:

            звать  здорово
Реплика 20  0.739    0.674

N-граммы (биграммы, только встречающиеся)

Реплика 21:

,бросить,заботиться,маленький,подобрать,прийтись,улица,аз,герд,дворняжка,девочка,два
Реплика 21,0.374,0.374,0.374,0.374,0.374,0.374,0.187,0.187,0.187,0.187,0.152

N-граммы (биграммы, только встречающиеся)

Реплика 22:

,молодец,планировать,путешествие,спасти,жизнь,новый,страна,два,здорово,лето,побывать,путешествовать,любить
Реплика 22,0.316,0.316,0.316,0.316,0.281,0.281,0.281,0.257,0.257,0.257,0.257,0.257,0.188

N-граммы (биграммы, только встречающиеся)

Реплика 23:

,грандиозный,другой,план,удаваться,страна,лето,побывать,пока
Реплика 23,0.384,0.384,0.384,0.384,0.342,0.312,0.312,0.312

N-граммы (биграммы, только встречающиеся)

Реплика 24:

            какой
Реплика 24    1.0

N-граммы (биграммы, только встречающиеся)

Реплика 25:

            родственник  россия  сначала  германия  поехать
Реплика 25        0.467   0.467    0.467     0.416    0.416

N-граммы (биграммы, только встречающиеся)

Реплика 26:

,группа,концерт,львов,музыка,океан,ходить,эльзить,слушать,вообще,какой,очень,рок,кстати,любить
Реплика 26,0.297,0.297,0.297,0.297,0.297,0.297,0.297,0.264,0.241,0.241,0.241,0.241,0.223,0.176

N-граммы (биграммы, только встречающиеся)

Реплика 27:

,нравиться,поп,рэп,часто,джаз,слушать,вообще,рок,любить
Реплика 27,0.371,0.371,0.371,0.371,0.331,0.331,0.302,0.302,0.221

N-граммы (биграммы, только встречающиеся)

Реплика 28:

,замок,красивый,особенно,родиться,германия,джаз,очень,понравиться,рок
Реплика 28,0.363,0.363,0.363,0.363,0.324,0.324,0.296,0.296,0.296

N-граммы (биграммы, только встречающиеся)

Реплика 29:

,быть,вставать,готовить,думать,завтра,кушать,ладный,ложиться,нужно,рано,семья,спать,пока,понравиться
Реплика 29,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.274,0.223,0.223

N-граммы (биграммы, только встречающиеся)

,аж два,аз герд,беларусь минск,бросить маленький,быть ложиться,вегаснуть черепаха,возле море,вообще любить,вообще рок,вообще часто,...,удаваться побывать,украина откуда,украина очень,улица бросить,фрукт дача,ходить концерт,хотя любить,часто слушать,черепаха матильда,эльзить очень
Реплика 1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 5,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
Реплика 6,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Реплика 8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 9,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Реплика 10,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0

### 5.4 Word2Vec

In [15]:
# Для Word2Vec нужен список предложений (токенов)
sentences = list(dialogue_df['lemmas'])
sentences_nonempty = [s for s in sentences if len(s) > 0]

w2v_model = Word2Vec(
    sentences=sentences_nonempty,
    vector_size=50,
    window=3,
    min_count=1,
    workers=2,
    seed=42,
    epochs=50
)

vocab = list(w2v_model.wv.key_to_index.keys())
print(f'Словарь Word2Vec ({len(vocab)} слов): {vocab}\n')

# вектор первого слова
if vocab:
    sample_word = vocab[0]
    print(f'Вектор слова "{sample_word}" (первые 10 измерений):')
    print(w2v_model.wv[sample_word][:10])

Словарь Word2Vec (127 слов): ['любить', 'море', 'украина', 'кстати', 'рок', 'очень', 'вообще', 'путешествовать', 'пока', 'какой', 'лето', 'собака', 'дача', 'побывать', 'здорово', 'два', 'понравиться', 'поехать', 'прогулка', 'подобрать', 'улица', 'бросить', 'маленький', 'пеший', 'заботиться', 'познакомиться', 'приятно', 'мечтать', 'звать', 'дачница', 'продавать', 'фрукт', 'овощ', 'продавец', 'откуда', 'новый', 'жизнь', 'заниматься', 'дело', 'прийтись', 'привет', 'джаз', 'страна', 'слушать', 'германия', 'выращивать', 'думать', 'родиться', 'замок', 'красивый', 'круто', 'беларусь', 'минск', 'рэп', 'особенно', 'быть', 'купить', 'поп', 'мочь', 'позволить', 'катя', 'ир', 'часто', 'ладный', 'путешествие', 'жить', 'выращивание', 'готовить', 'замечательный', 'твой', 'вставать', 'рано', 'рада', 'нужно', 'знакомство', 'всё', 'неплохо', 'недавно', 'найти', 'работа', 'специальность', 'дизайнер', 'завтра', 'спать', 'ложиться', 'нравиться', 'возле', 'кушать', 'животное', 'кошатница', 'кот', 'вегаснуть', 'черепаха', 'матильда', 'аж', 'план', 'аз', 'герд', 'девочка', 'дворняжка', 'грандиозный', 'другой', 'удаваться', 'спасти', 'молодец', 'сначала', 'хотя', 'планировать', 'россия', 'музыка', 'группа', 'эльзить', 'океан', 'обожать', 'концерт', 'город', 'крым', 'ждать', 'дождаться', 'ходить', 'львов', 'стать', 'родственник', 'друг', 'машина', 'поэтому', 'семья']

Вектор слова "любить" (первые 10 измерений):
[-0.01765151  0.0093045   0.00397445 -0.0017817  -0.00621142  0.01690843
 -0.01785933  0.01342779 -0.0156237  -0.01546216]

### 5.5 Топ-10 важных слов (по TF-IDF)

In [16]:
# Суммируем TF-IDF веса по всем репликам - это рейтинг слов
word_scores = tfidf_df.sum(axis=0).sort_values(ascending=False)

top10 = word_scores.head(10)
top10_df = top10.reset_index()
top10_df.columns = ['Слово', 'Суммарный TF-IDF']
top10_df.index += 1

print('Топ-10 важных слов диалога (TF-IDF):')
display(top10_df)

Топ-10 важных слов диалога (TF-IDF):

      Слово  Суммарный TF-IDF
1    любить             1.941
2     какой             1.786
3    привет             1.707
4      море             1.693
5   украина             1.625
6   здорово             1.473
7    собака             1.172
8    кстати             1.152
9      дело             1.133
10    звать             1.076